name: CI Pipeline

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55

      - name: Build Docker
        run: make build-docker
